[cursor.style]
shape = "Beam"

[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
history = 10000

[window]
dynamic_padding = true
opacity = 0.9
blur = true

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 5
y = 5
