[cursor.style]
shape = "Beam"

[font]
size = 18.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[scrolling]
history = 10000

[window]
dynamic_padding = true
opacity = 0.9
blur = true

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 5
y = 5
