- name:
  hosts: localhost
  connection: local
  tasks:

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Packages and Tools roles
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    - ansible.builtin.import_role:
        name: packages
      tags: ["never", "setup", "packages"]

    - ansible.builtin.import_role:
        name: docker
      tags: ["never", "setup", "docker"]

    - ansible.builtin.import_role:
        name: azcli
      tags: ["never", "setup", "azcli"]

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Configuration roles
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    - ansible.builtin.import_role:
        name: tmux
      tags: ["never", "setup", "tmux"]

    - ansible.builtin.import_role:
        name: ssh
      tags: ["never", "setup", "ssh"]
