- name:
  hosts: localhost
  connection: local
  tasks:

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Packages and Tools roles
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    - ansible.builtin.import_role:
        name: packages
      tags: ["never", "setup", "packages"]
      when: ansible_os_family == "Debian"

    - ansible.builtin.import_role:
        name: docker
      tags: ["never", "setup", "docker"]
      when: ansible_os_family == "Debian"

    - ansible.builtin.import_role:
        name: azcli
      tags: ["never", "setup", "azcli"]
      when: ansible_os_family == "Debian"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Configuration roles
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    - ansible.builtin.import_role:
        name: tmux
      tags: ["never", "setup", "tmux"]

    - ansible.builtin.import_role:
        name: ssh
      tags: ["never", "setup", "ssh"]

    - ansible.builtin.import_role:
        name: fonts
      tags: ["never", "setup", "fonts"]
