theme = "base16_transparent"

[editor]
line-number = "absolute"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-q = ":q!"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
