return {
    { 'olimorris/onedarkpro.nvim',        lazy = true },
    { 'arcticicestudio/nord-vim',         lazy = true },
    { 'projekt0n/github-nvim-theme',      lazy = true },
    { 'rose-pine/neovim',                 lazy = true },
    { 'aliqyan-21/darkvoid.nvim',         lazy = true },
    { "folke/tokyonight.nvim",            lazy = true },
    { "mhartington/oceanic-next",         lazy = true },
    { "EdenEast/nightfox.nvim",           lazy = true },
    { "catppuccin/nvim",                  lazy = true,        name = "catppuccin", priority = 1000 },
    { 'nyoom-engineering/oxocarbon.nvim', lazy = true },
    { 'sainnhe/everforest',               lazy = true },
    { 'rafi/awesome-vim-colorschemes',    lazy = true },
    { 'navarasu/onedark.nvim',            lazy = true },
    { 'nickkadutskyi/jb.nvim',            lazy = true },
    { 'Everblush/nvim',                   name = 'everblush', lazy = false },
}
