- name:
  hosts: all
  tasks:

    - ansible.builtin.ping:

    - name: Clone TPM tmux plugin manager
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm

