# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Load custom files
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Load git completion and prompt.sh
if [ -f ~/.git-completion.bash ]; then
    . ~/.git-completion.bash
fi

# Set PATH, MANPATH, etc., for Homebrew.
if [ -f "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
  eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
fi
if [ -f "/opt/homebrew/bin/brew" ]; then
  eval $(/opt/homebrew/bin/brew shellenv)
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

# Use bash-completion, if available
[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
    . /usr/share/bash-completion/bash_completion

# kubectl completions
if [ -x "$(command -v kubectl)" ]; then
        source <(kubectl completion bash)
fi

# kustomize completions
if [ -x "$(command -v kustomize)" ]; then
        source <(kustomize completion bash)
fi

# if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
#         tmux attach -t default || tmux new -s default
# fi

if [ -f "$HOME/.cargo/env" ]; then
  . "$HOME/.cargo/env"
fi

# Local aliasses
if [ -f "$HOME/.local_aliases" ]; then
    . "$HOME/.local_aliases"
fi

# This is needed for WSL to communicate with SSH Agent on Windows
if [ -f "$HOME/.local/bin/wsl-ssh-agent-relay" ]; then
    ${HOME}/.local/bin/wsl-ssh-agent-relay start
    export SSH_AUTH_SOCK=${HOME}/.ssh/wsl-ssh-agent.sock
fi

# Load direnv
if [ -x "$(command -v direnv)" ]; then
  eval "$(direnv hook bash)"
fi

# Load Zellij
# if command -v zellij &> /dev/null; then
#   eval "$(zellij setup --generate-auto-start bash)"
# fi

# Load FZF
if command -v fzf &> /dev/null; then
    eval "(fzf --bash)"
fi

. "$HOME/.local/share/../bin/env"
